# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'map_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(252, 319)
        Form.setMinimumSize(QtCore.QSize(252, 319))
        Form.setMaximumSize(QtCore.QSize(252, 319))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.map_lab = QtWidgets.QLabel(self.frame)
        self.map_lab.setMinimumSize(QtCore.QSize(0, 200))
        self.map_lab.setScaledContents(True)
        self.map_lab.setObjectName("map_lab")
        self.verticalLayout.addWidget(self.map_lab)
        self.map_info = QtWidgets.QLabel(self.frame)
        self.map_info.setAlignment(QtCore.Qt.AlignCenter)
        self.map_info.setObjectName("map_info")
        self.verticalLayout.addWidget(self.map_info)
        self.verticalLayout_2.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.map_lab.setText(_translate("Form", "여기에 그래프 사진"))
        self.map_info.setText(_translate("Form", "여기에 그래프 이름"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
