# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'seoul_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(520, 148)
        Form.setStyleSheet("")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.img_label = QtWidgets.QLabel(Form)
        self.img_label.setMinimumSize(QtCore.QSize(120, 0))
        self.img_label.setMaximumSize(QtCore.QSize(120, 120))
        self.img_label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 60px;")
        self.img_label.setScaledContents(True)
        self.img_label.setObjectName("img_label")
        self.horizontalLayout.addWidget(self.img_label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.name_lab = QtWidgets.QLabel(Form)
        self.name_lab.setObjectName("name_lab")
        self.verticalLayout.addWidget(self.name_lab)
        self.type_lab = QtWidgets.QLabel(Form)
        self.type_lab.setObjectName("type_lab")
        self.verticalLayout.addWidget(self.type_lab)
        self.location_lab = QtWidgets.QLabel(Form)
        self.location_lab.setObjectName("location_lab")
        self.verticalLayout.addWidget(self.location_lab)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.img_label.setText(_translate("Form", "TextLabel"))
        self.name_lab.setText(_translate("Form", "이름"))
        self.type_lab.setText(_translate("Form", "업종"))
        self.location_lab.setText(_translate("Form", "위치"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
